version: "3"
services:
  epics:
    image: nsls2/epics-docker:latest
    volumes:
      - ./ophyd_AD_test:/tmp/ophyd_AD_test/
    tty: true
  area-detector:
    image: prjemian/synapps-6.1-ad-3.7:latest
    environment: 
      - AD_PREFIX="ADSIM:"
    volumes:
      - ./ophyd_AD_test:/tmp/ophyd_AD_test/
    command: bash -c "iocSimDetector/simDetector.sh start && tail -f /dev/null"
    tty: true
  pyepics:
    image: nsls2/pyepics-docker:latest
    tty: true
  ophyd:
    build: ./ophyd
    ports:
      - "8888:8888"
    command: /scripts/startup.sh
    volumes:
      - ./ophyd_AD_test:/tmp/ophyd_AD_test/
      - ./ophyd/notebooks:/opt/notebooks
      - ./ophyd/scripts:/scripts
    tty: true