version: "3"
services:
  #epics:
  #  image: nsls2/epics-docker:latest
  #  volumes:
  #    - ./ophyd_AD_test:/tmp/ophyd_AD_test/
  #  tty: true
  #pyepics:
  #  image: nsls2/pyepics-docker:latest
  #  tty: true
  #zookeeper:
  #  image: wurstmeister/zookeeper:latest
  #  ports:
  #    - 2181:2181    
  #  tty: true
  #kafka:
  #  image: wurstmeister/kafka:latest
  #  depends_on:
  #    - zookeeper    
  #  environment: 
  #    HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
  #    KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #  ports:
  #    - 9092:9092      
  #  tty: true
  ophyd-bluesky:
    image:  dpi/ophyd-bluesky:latest
    build:
      context: .
    volumes:
      # Uncomment the next line to use Docker from inside the container. See https://aka.ms/vscode-remote/samples/docker-from-docker-compose for details.    
      - /var/run/docker.sock:/var/run/docker.sock 
      - ../notebooks:/notebooks
      - ../scripts:/scripts
      - ../test:/test
    tty: true